# Generated by Django 2.2.28 on 2022-05-02 07:24

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 14 digits allowed.", regex='^\\+?1?\\d{9,14}$')])),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('zip', models.CharField(blank=True, max_length=8)),
                ('state', models.CharField(blank=True, max_length=64)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('dry_cleaning', models.BooleanField(default=False)),
                ('hang', models.BooleanField(default=True)),
                ('special_detergent', models.BooleanField(default=True)),
                ('special_softener', models.BooleanField(default=True)),
                ('intensive_clean', models.BooleanField(default=True)),
                ('ironing', models.BooleanField(default=True)),
                ('priority', models.BooleanField(default=True)),
                ('preferred_language', models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish')], default='English', max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
