# Generated by Django 2.2.28 on 2022-06-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='service-provider/profile'),
        ),
    ]
