# Generated by Django 2.2.28 on 2022-07-09 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0008_2_5'),
        ('serviceproviders', '0002_auto_20220629_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='account',
            field=models.ForeignKey(blank=True, help_text="The service provider's Stripe Account object, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.Account'),
        ),
    ]
