# Generated by Django 2.2.28 on 2022-07-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0003_serviceprovider_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='generated_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
