# Generated by Django 2.2.28 on 2022-07-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0004_auto_20220710_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='number_of_orders',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
