# Generated by Django 2.2.28 on 2022-07-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_auto_20220709_1904'),
        ('serviceproviders', '0005_serviceprovider_number_of_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='skipped_orders',
            field=models.ManyToManyField(blank=True, to='order.Order'),
        ),
    ]
