# Generated by Django 2.2.28 on 2022-06-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='dispute/images'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
