# Generated by Django 2.2.28 on 2022-06-08 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
