# Generated by Django 2.2.28 on 2022-07-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_total_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='number_of_requests',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
