# Generated by Django 2.2.28 on 2022-05-01 13:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20220501_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='intensive_clean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='items_to_iron',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), default=list, size=None),
        ),
        migrations.AddField(
            model_name='order',
            name='special_detergent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='special_softener',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('Dry Cleaning', 'Dry Cleaning'), ('Wash and Fold', 'Wash and Fold')], default='Wash and Fold', max_length=32),
        ),
    ]
