# Generated by Django 2.2.28 on 2022-06-08 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_item_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
    ]
