# Generated by Django 2.2.28 on 2022-06-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fold',
        ),
        migrations.RemoveField(
            model_name='order',
            name='hang',
        ),
        migrations.AlterField(
            model_name='order',
            name='special_detergent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='special_softener',
            field=models.BooleanField(default=False),
        ),
    ]
