# Generated by Django 2.2.28 on 2022-07-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_auto_20220629_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='weight_price',
        ),
        migrations.AddField(
            model_name='order',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
